### ISSUE TITLE
Update breaking slack github actions workflow

### ISSUE THREAD

**Issue by EKarpinsky** [SamVerschueren/decode-uri-component#9]
Latest updates broke our Github Actions workflow which posts alerts to slack:
`Error:   web-api:WebClient:0 failed to match all allowed schemas [json-pointer:/blocks/5/text]
Error:   web-api:WebClient:0 must be less than 3001 characters [json-pointer:/blocks/5/text/text]`

**Comment by SamVerschueren** [comment]
I think the update made sure the decoding is now correct and doesn't drop characters randomly. That might be the reason you are now over 3001 characters instead of under it. Maybe check the code and see if the URL can be shortened somehow. Or if it's a bug on `decode-uri-component`, I have to know what it now does instead of what it did before.

**Comment by SamVerschueren** [comment]
Closing this issue. Feel free to create a new issue if you think it's because of this library.
